[phases.setup]
nixPkgs = ['...', 'php84', 'php84Packages.composer', 'php84Extensions.zip', 'php84Extensions.gd', 'php84Extensions.pdo', 'php84Extensions.pdo_sqlite']

[phases.install]
cmds = ['composer install --no-dev --optimize-autoloader --no-interaction --ignore-platform-reqs']

[phases.build]
cmds = [
    'php artisan config:cache',
    'php artisan route:cache',
    'php artisan view:cache'
]

[start]
cmd = 'mkdir -p database && touch database/database.sqlite && chmod 775 database/database.sqlite && php artisan migrate --force && php artisan db:seed --force && php artisan serve --host=0.0.0.0 --port=$PORT'
